### ISSUE TITLE
consider leveraging cf-routing-release for web routing

### ISSUE THREAD

**Issue by aegershman** [doomsday-project/doomsday-boshrelease#3]
In order to piggyback off of existing dns, certificates, etc., of a cloud foundry deployment, you might consider including the `cf-routing-release` and an opsfile which hooks the doomsday deployment up to the cf route registrar.

example: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-cf-route-registrar.yml

just a thought, no worries if not. after all, if you were to deploy this to take advantage of cf's routing release, you might just as well deploy it on CF itself (which is what I do anyway), but alas, just a suggestion. feel free to close whenever. Thanks!

**Comment by thomasmitchell** [comment]
moved this into the boshrelease as it has more to do with the deployment/operation of the project in bosh-land than the project itself.

For this to make sense, we need to first actually make an example manifest with ops-files. That in itself is difficult due to the configuration of doomsday being so different from environment-to-environment. That said, I do like leveraging route registrar in environments without easily accessible internal DNS, and will definitely keep this in mind if we make an ops file setup in this repo (or it's own doomsday-deployments repo, in which case, this issue will get transferred again :P)
